#!/bin/sh

# Version string
BUILD_ID="1.0.0"

# Mesage symbols
MSG_OK="[  OK  ] :"
MSG_FAIL="[ FAIL ] :"
MSG_NOTE="[ NOTE ] :"

# Print version string
echo "$MSG_NOTE pake $BUILD_ID"

# Basic configuration
# CC=
# ARGS=
# SOURCE_FILE=
# OUT_FILE=

# Clean up
if [ -f "$OUT_FILE" ]; then
 rm $OUT_FILE
fi

# Checks if the command ran before worked
# This should ONLY be used after every compilation
check_bin() {
	if [ $? -ne 0 ]; then
  		echo "$MSG_FAIL failed to compile $SOURCE_FILE"
		echo "$MSG_FAIL terminating program early due to above error(s)"
		exit 1
	else
  		echo "$MSG_OK compiled $SOURCE_FILE successfully."
		
		# Either run or quit the build
		case "$1" in
			"run")
				echo "$MSG_NOTE now running executable '$OUT_FILE'"
				./$OUT_FILE
			;;

			*)
				# Do nothing
			;;
		esac
	fi 
}

# Allows for specific build instructions
# see the README for more details.
case "$1" in
	"build")
	  # $CC $ARGS $SOURCE_FILE -o $OUT_FILE
	  # check_bin
	;;

	*)
		echo "$MSG_NOTE no arguments given"
	;;
esac
