#!/bin/sh

# version string
VERSION="2024.1.25.12.32"

# mesage symbols
MSG_OK="[  OK  ] :"
MSG_FAIL="[ FAIL ] :"
MSG_NOTE="[ NOTE ] :"

# print version string
echo "$MSG_NOTE pake $VERSION"

# basic configuration
# CC=
# ARGS=
# SOURCE_FILE=
# OUT_FILE=

# clean up
if [ -f "$OUT_FILE" ]; then
 rm $OUT_FILE
fi

# checks if the command ran before worked
# this should ONLY be used after every compilation
check_bin() {
	if [ $? -ne 0 ]; then
  		echo "$MSG_FAIL failed to compile $SOURCE_FILE"
		echo "$MSG_FAIL terminating program early due to above error(s)"
		exit 1
	else
  		echo "$MSG_OK compiled $SOURCE_FILE successfully."
		
		# either run or quit the build
		case "$1" in
			"run")
				echo "$MSG_NOTE now running executable '$OUT_FILE'"
				./$OUT_FILE
			;;

			*)
				echo "$MSG_NOTE check_bin(): no argument given, skipping binary handling"
			;;
		esac
	fi 
}

# allows for specific build instructions
# see the README for more details.
case "$1" in
	#"build")
		# echo "$MSG_NOTE attempting to compile $SOURCE_FILE to $OUT_FILE"
	  	# $CC $ARGS $SOURCE_FILE -o $OUT_FILE
	  	# check_bin $2 
	#;;

	#"push")
		# echo "$MSG_NOTE attempting to push changes to main"
		# git add *
		# git commit -a
		# git push -u origin main
	#;;

	*)
		echo "$MSG_NOTE no arguments given"
	;;
esac
